### ISSUE TITLE
Unable to run the Quare app directly via "docker compose up"

### ISSUE THREAD

**Issue by lifan0127** [uniba-mi/quare#3]
Hello, I came to test this software after reading your paper: "Specification and Validation of Quality Criteria for Git Repositories using RDF and SHACL"

The README states that we can launch the app via `docker compose up` after cloning the repository. In my experience (OS: Ubuntu 20.04), two additional steps are needed:

1. In the frontend directory, run `npm install` to install all the dependencies.
2. In the backend directory, run `chmod +x backend_api.py` to add execution permission.

Afterwards, `docker compose up` works correctly.

Thank you!

**Comment by leonmartin** [comment]
Hi, thank you for raising this issue. It should be fixed now. Thanks for trying out our tool!
